version: "2"
services:
  etutor-fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: etutor-fe
    restart: always
  etutor-be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: etutor-be
    restart: always
